# =============================================================================
# prject  : R Programming hw2
# author  : bonzoyang
# discribe: makeCacheMatrix: make a special matrix to cache it's inverse.
#           cacheSolve     : resolve inversed matrix if inversed matrix wasn't
#                            cached before.
# =============================================================================

## makeCacheMatrix 
# returns a special list containing a specified matrix and it's invere
# 4 utility functions are associated with this special list
#
# set(mtx)     : set matrix as input specified matrix mtx, and reset it's  
#                inverse that cached before.
# get()        : retrive the matrix.
# setinvx(imtx): set inverse matrix as input specified inverse matrix imtx.
# getinvx()    : retrive inverse matrix.
makeCacheMatrix <- function(x = matrix()) {
    # x    : matrix
    # invx : inverse matrix
    invx <- NULL
    
    set <- function(mtx){
        x <<- mtx
        invx <<- NULL
    }
    
    get <- function() x
    
    setinvx <- function(imtx) invx <<- imtx
    getinvx <- function() invx
    list( set = set, get = get, setinvx = setinvx, getinvx = getinvx)
}


## cacheSolve
# returns inverse matrix of special list generated by makeCacheMatrix()
# if inverse matrix has been solved before, just return the inverse from cache.
# if it hasn't, solve the inverse matrix by solve(). 
cacheSolve <- function(x, ...) {
    invx <- x$getinvx()
    if(! is.null(invx)){
        message("getting cached inverse matrix")
        return(invx)
    }
    mtx <- x$get()
    imtx <- solve(mtx)
    x$setinvx(imtx)
    #x$getinvx()
    imtx
}
